const majorWorldCities = [
    'Tokyo',
    'Delhi',
    'Shanghai',
    'Beijing',
    'Mumbai',
    'Istanbul',
    'Lahore',
    'Bangkok',
    'Kolkata',
    'Buenos Aires',
    'Kinshasa',
    'Manila',
    'Cairo',
    'Dhaka',
    'Mexico City',
    'Lima',
    'New York City',
    'Bangalore',
    'London',
    'Ho Chi Minh City',
    'Lagos',
    'Jakarta',
    'Seoul',
    'Sao Paulo',
    'Chennai',
    'Bogota',
    'Lusaka',
    'Chongqing',
    'Tehran',
    'Hong Kong',
    'Ahmedabad',
    'Chengdu',
    'Kuala Lumpur',
    'Rio de Janeiro',
    'Los Angeles',
    'Tianjin',
    'Budapest',
    'Warsaw',
    'Hyderabad',
    'Johannesburg',
    'Santiago',
    'Nairobi',
    'Chicago',
    'Baghdad',
    'Hanoi',
    'Toronto',
    'Philadelphia',
    'Luanda',
    'Dallas',
    'Belgrade',
    'Washington D.C.',
    'Medellin',
    'Brisbane',
    'Melbourne',
    'Milan',
    'Zurich',
    'Montreal',
    'Seattle',
    'Cape Town',
    'Caracas',
    'Vienna',
    'San Francisco',
    'Osaka',
    'Copenhagen',
    'Barcelona',
    'Portland',
    'Lyon',
    'Berlin',
    'Dublin',
    'Stockholm',
    'Vancouver',
    'Prague',
    'Hamburg',
    'Munich',
    'Amsterdam',
    'Oslo',
    'Frankfurt',
    'Kyoto',
    'Edinburgh',
    'Moscow',
    'Madrid',
    'Athens',
    'Naples',
    'Brussels',
    'Geneva',
    'Rome',
    'Paris',
    'Sydney',
    'Miami',
    'Dubai',
    'San Diego',
    'San Antonio',
    'Austin',
    'Helsinki',
    'Detroit',
    'Manchester',
    'Denver',
    'Perth',
    'Lisbon',
    'Detroit',
  ];
  
  export default majorWorldCities;
  
  
  export { majorWorldCities };
